/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Professor;

import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author anzal
 */
public class CreateCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCourseJPanel
     */
    
javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    private ProfessorLogin loggedinUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    private Course cos;
    
    public CreateCourseJPanel(JPanel workArea, ProfessorLoginHistory history1 , ProfessorLogin loggedinUser,CourseHistory c_history,Course cos,StudentLoginHistory history,studentLogin loggedInUser,EnrollmentHistory enrollmentList,Enrollment enroll) {
    
        initComponents();
        this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.loggedinUser = loggedinUser;
        this.history1 = history1;
        this.enroll = enroll;
        this.cos = cos;
        customizeComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseDesc = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCourseDesc = new javax.swing.JTextArea();
        comboTerm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COURSE CREATION");

        lblCourseID.setText("Course ID :");

        lblCourseName.setText("Course Name : ");

        lblCourseDesc.setText("Course Description :");

        txtCourseDesc.setColumns(20);
        txtCourseDesc.setRows(5);
        jScrollPane1.setViewportView(txtCourseDesc);

        comboTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023", "Spring 2024", "Fall 2024"}));

        jLabel2.setText("Select a Term :");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/online-course.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(70, 70, 70)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseID)
                            .addComponent(lblCourseName)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCourseID)
                                .addComponent(txtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseID)
                            .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseName)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseDesc)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnSave)))
                    .addComponent(jLabel3))
                .addContainerGap(461, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        ViewProfessorPortalJPanel panel = new ViewProfessorPortalJPanel(workArea,history1,loggedinUser,c_history,cos,history,loggedInUser,enrollmentList,enroll);
        workArea.add("ViewProfessorPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String course_id = txtCourseID.getText();
        String course_name = txtCourseName.getText();
        String course_desc = txtCourseDesc.getText();
        String term = comboTerm.getSelectedItem().toString();
        
        Course cou = c_history.addnewcourse();
        cou.setCourse_id(course_id);
        cou.setCourse_name(course_name);
        cou.setCourse_description(course_desc);
        cou.setTerm(((String) comboTerm.getSelectedItem()).trim());
        
       // createNewCourse(course_id, course_name, course_desc, term, loggedinUser);
    
        JOptionPane.showMessageDialog(this,"New Course added");
        
        
        
        txtCourseID.setText("");
        txtCourseName.setText("");
        txtCourseDesc.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        Font labelFont = new Font("Tahoma", Font.BOLD, 12);
        Color textColor = new Color(236, 240, 241);

        lblCourseID.setFont(labelFont);
        lblCourseID.setForeground(textColor);
        lblCourseName.setFont(labelFont);
        lblCourseName.setForeground(textColor);
        lblCourseDesc.setFont(labelFont);
        lblCourseDesc.setForeground(textColor);
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 28));
        jLabel1.setForeground(textColor);
        jLabel2.setFont(labelFont);
        jLabel2.setForeground(textColor);

        // Set text field and text area styles
        Color textFieldBackground = new Color(52, 73, 94);
        Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

        txtCourseID.setBackground(textFieldBackground);
        txtCourseID.setForeground(textColor);
        txtCourseID.setBorder(textFieldBorder);
        txtCourseName.setBackground(textFieldBackground);
        txtCourseName.setForeground(textColor);
        txtCourseName.setBorder(textFieldBorder);
        txtCourseDesc.setBackground(textFieldBackground);
        txtCourseDesc.setForeground(textColor);
        txtCourseDesc.setBorder(textFieldBorder);

        // Set combo box style
        comboTerm.setBackground(textFieldBackground);
        comboTerm.setForeground(textColor);

        // Set button style
        Color buttonBackground = new Color(52, 152, 219);
        Color buttonTextColor = new Color(255, 255, 255);
        Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

        btnBack.setBackground(buttonBackground);
        btnBack.setForeground(buttonTextColor);
        btnBack.setBorder(buttonBorder);
        btnSave.setBackground(buttonBackground);
        btnSave.setForeground(buttonTextColor);
        btnSave.setBorder(buttonBorder);
    }
    
//    public void createNewCourse(String courseId, String courseName, String courseDesc, String term, ProfessorLogin professor) {
//    Course newCourse = new Course();
//    newCourse.setCourse_id(courseId);
//    newCourse.setCourse_name(courseName);
//    newCourse.setCourse_description(courseDesc);
//    newCourse.setTerm(term);
//    newCourse.setProfessor(professor);
//    c_history.addnewcourse(); // Note: not passing newCourse here
//    professor.incrementNumberOfCoursesCreated();
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboTerm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseDesc;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JTextArea txtCourseDesc;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    // End of variables declaration//GEN-END:variables
}
