/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Professor;

import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anzal
 */
public class ManageCourseCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCourseCatalogJPanel
     */
    

    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    private ProfessorLogin loggedinUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    private Course cos;
    
   public ManageCourseCatalogJPanel(JPanel workArea, ProfessorLoginHistory history1 , ProfessorLogin loggedinUser,CourseHistory c_history,Course cos,StudentLoginHistory history,studentLogin loggedInUser,EnrollmentHistory enrollmentList,Enrollment enroll) {
        
   
       initComponents();
       this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.loggedinUser = loggedinUser;
        this.history1 = history1;
        this.enroll = enroll;
        this.cos = cos;
   
       populateTable();
       customizeComponents();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnViewDetails = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE COURSES");

        tblCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Course Description", "Term"
            }
        ));
        jScrollPane1.setViewportView(tblCourse);

        btnSearch.setText("Search :");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/online-course.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteCourse)
                        .addGap(800, 800, 800))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewDetails)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(32, 32, 32)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(300, 300, 300))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewDetails))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteCourse)
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblCourse.getSelectedRow();
        
        if(selectedRow >= 0){
            int dailogButton = JOptionPane.YES_NO_OPTION;
            int dailogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the course details?","Warning",dailogButton);
            
            if(dailogResult == JOptionPane.YES_OPTION){
                Course course = (Course) tblCourse.getValueAt(selectedRow, 0);
                c_history.deleteCourse(course);
                
                populateTable();
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblCourse.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view courses", "Warning", JOptionPane.WARNING_MESSAGE);
       
        }else{
            
            Course cos1 = (Course) tblCourse.getValueAt(selectedRow, 0);
            ViewCourseCatalogJPanel panel = new ViewCourseCatalogJPanel(workArea,history1,loggedinUser,c_history,cos1,history,loggedInUser,enrollmentList,enroll);
            workArea.add("ViewCourseCatalogJPanel", panel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
            
        }
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        ViewProfessorPortalJPanel panel = new ViewProfessorPortalJPanel(workArea,history1,loggedinUser,c_history,cos,history,loggedInUser,enrollmentList,enroll);
        workArea.add("ViewProfessorPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        Course course = c_history.searchCourse(txtSearch.getText());
        
         if(course == null){
            JOptionPane.showMessageDialog(null, "Course ID you entered doesnot exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             
             ViewCourseCatalogJPanel panel = new ViewCourseCatalogJPanel(workArea,history1,loggedinUser,c_history,course,history,loggedInUser,enrollmentList,enroll);
            workArea.add("ViewCourseCatalogJPanel", panel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
             
         }
         
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       
       
//        boolean credentialsMatch = false;
//        
//        for (ProfessorLogin user : history1.getHistory()) {
//            if (user.getUsername().equals(enteredUsername) && user.getPassword().equals(enteredPassword)) {
//                credentialsMatch = true;
//                break;
//            } 
//        }
        
        DefaultTableModel dtm = (DefaultTableModel) tblCourse.getModel();
        dtm.setRowCount(0);
        //String professorUsername = loggedinUser.getUsername();
        for(Course cos1: c_history.getHistory()){
          // for(ProfessorLogin prof : history1.getHistory()){ 
            //if (prof.getTemp().equals(professorUsername)) {
            Object[] row = new Object[4];
            row[0] = cos1;
            row[1] = cos1.getCourse_name();
            row[2] = cos1.getCourse_description();
            row[3] = cos1.getTerm();
            
            dtm.addRow(row);
            
            //}
            //}
    
    }
    }
    
    private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    Font labelFont = new Font("Tahoma", Font.BOLD, 12);
    Color textColor = new Color(236, 240, 241);

    jLabel1.setFont(new Font("Tahoma", Font.BOLD, 28));
    jLabel1.setForeground(textColor);

    // Set table style
    tblCourse.setBackground(new Color(52, 73, 94));
    tblCourse.setForeground(textColor);
    tblCourse.setFont(new Font("Tahoma", Font.PLAIN, 12));
    jScrollPane1.getViewport().setBackground(new Color(44, 62, 80));

    // Set table header style
    tblCourse.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
    tblCourse.getTableHeader().setBackground(new Color(52, 73, 94));
    tblCourse.getTableHeader().setForeground(new Color(44, 62, 80));

    // Set text field style
    Color textFieldBackground = new Color(52, 73, 94);
    Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

    txtSearch.setBackground(textFieldBackground);
    txtSearch.setForeground(textColor);
    txtSearch.setBorder(textFieldBorder);

    // Set button style
    Color buttonBackground = new Color(52, 152, 219);
    Color buttonTextColor = new Color(255, 255, 255);
    Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

    btnSearch.setBackground(buttonBackground);
    btnSearch.setForeground(buttonTextColor);
    btnSearch.setBorder(buttonBorder);
    btnViewDetails.setBackground(buttonBackground);
    btnViewDetails.setForeground(buttonTextColor);
    btnViewDetails.setBorder(buttonBorder);
    btnDeleteCourse.setBackground(buttonBackground);
    btnDeleteCourse.setForeground(buttonTextColor);
    btnDeleteCourse.setBorder(buttonBorder);
    btnBack.setBackground(buttonBackground);
    btnBack.setForeground(buttonTextColor);
    btnBack.setBorder(buttonBorder);
}

    
}
