/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Professor;

import Business.Admin.ManageAdminJPanel;
import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author anzal
 */
public class ProfessorLoginPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorLoginPageJPanel
     */
    
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedinUser;
    private ProfessorLogin loggedInUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    private Course cos;

    public ProfessorLoginPageJPanel(JPanel workArea, ProfessorLoginHistory history1 , ProfessorLogin loggedInUser,CourseHistory c_history,Course cos,StudentLoginHistory history,studentLogin loggedinUser,EnrollmentHistory enrollmentList,Enrollment enroll) {
    
    //public ProfessorLoginPageJPanel(JPanel workArea,ProfessorLoginHistory history1, ProfessorLogin loggedInUser) {
     
    initComponents();
        this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.loggedinUser = loggedinUser;
        this.history1 = history1;
        this.enroll = enroll;
        this.cos = cos;
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleProfLogin = new javax.swing.JLabel();
        lblProfUsername = new javax.swing.JLabel();
        lblProfPass = new javax.swing.JLabel();
        txtProfUsername = new javax.swing.JTextField();
        txtProfPass = new javax.swing.JPasswordField();
        btnProfLogin = new javax.swing.JButton();
        lblAdminImage = new javax.swing.JLabel();

        lblTitleProfLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleProfLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleProfLogin.setText("PROFESSOR LOGIN PAGE");

        lblProfUsername.setText("Username :");

        lblProfPass.setText("Password : ");

        btnProfLogin.setText("Login");
        btnProfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfLoginActionPerformed(evt);
            }
        });

        lblAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/login-ext.png"))); // NOI18N
        lblAdminImage.setMaximumSize(new java.awt.Dimension(2308, 2002));
        lblAdminImage.setMinimumSize(new java.awt.Dimension(2308, 2002));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(575, 575, 575)
                .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleProfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProfPass)
                            .addGap(18, 18, 18)
                            .addComponent(txtProfPass))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProfUsername)
                            .addGap(18, 18, 18)
                            .addComponent(txtProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnProfLogin)))
                .addGap(590, 590, 590))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblTitleProfLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfUsername)
                    .addComponent(txtProfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfPass)
                    .addComponent(txtProfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnProfLogin)
                .addGap(500, 500, 500))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfLoginActionPerformed
        // TODO add your handling code here:
        
        if (txtProfUsername.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter the username");
            } else if (txtProfPass.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Please enter the password");
            } else {
            String enteredUsername = txtProfUsername.getText();
            String enteredPassword = new String(txtProfPass.getPassword());
            
             // Verify credentials with data in history ArrayList
            boolean credentialsMatch = false;
            
            for (ProfessorLogin user : history1.getHistory()) {
            if (user.getUsername().equals(enteredUsername) && user.getPassword().equals(enteredPassword)) {
                credentialsMatch = true;
                break;
            } 
        }
            
            if (credentialsMatch) {
                JOptionPane.showMessageDialog(null, "Login Successful");
                
                //ProfessorLogin loggedInUser = null;
                
                 for (ProfessorLogin user : history1.getHistory()) {
                if (user.getUsername().equals(enteredUsername) && user.getPassword().equals(enteredPassword)) {
                    loggedInUser = user;
                    break;
            }
        }

         if (loggedInUser != null) {
        ViewProfessorPortalJPanel panel = new ViewProfessorPortalJPanel(workArea,history1,loggedInUser,c_history,cos,history,loggedinUser,enrollmentList,enroll);
        workArea.add("ViewProfessorPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);}
        else{
            JOptionPane.showMessageDialog(null, "User not found!", "Message", JOptionPane.ERROR_MESSAGE);
        }
                    
             }
             else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!", "Message", JOptionPane.ERROR_MESSAGE);
            }}     
    }//GEN-LAST:event_btnProfLoginActionPerformed

    private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        Font labelFont = new Font("Tahoma", Font.BOLD, 12);
        Color textColor = new Color(236, 240, 241);

        lblTitleProfLogin.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblTitleProfLogin.setForeground(textColor);

        lblProfUsername.setFont(labelFont);
        lblProfUsername.setForeground(textColor);
        lblProfPass.setFont(labelFont);
        lblProfPass.setForeground(textColor);

        // Set text field and password field styles
        Color textFieldBackground = new Color(52, 73, 94);
        Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

        txtProfUsername.setBackground(textFieldBackground);
        txtProfUsername.setForeground(textColor);
        txtProfUsername.setBorder(textFieldBorder);
        txtProfPass.setBackground(textFieldBackground);
        txtProfPass.setForeground(textColor);
        txtProfPass.setBorder(textFieldBorder);

        // Set button style
        Color buttonBackground = new Color(52, 152, 219);
        Color buttonTextColor = new Color(255, 255, 255);
        Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

        btnProfLogin.setBackground(buttonBackground);
        btnProfLogin.setForeground(buttonTextColor);
        btnProfLogin.setBorder(buttonBorder);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProfLogin;
    private javax.swing.JLabel lblAdminImage;
    private javax.swing.JLabel lblProfPass;
    private javax.swing.JLabel lblProfUsername;
    private javax.swing.JLabel lblTitleProfLogin;
    private javax.swing.JPasswordField txtProfPass;
    private javax.swing.JTextField txtProfUsername;
    // End of variables declaration//GEN-END:variables
}
