/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Professor;

import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author anzal
 */
public class ViewProfessorAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfessorAccountJPanel
     */
  

   javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    private ProfessorLogin loggedinUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    private Course cos;
    
    public ViewProfessorAccountJPanel(JPanel workArea, ProfessorLoginHistory history1 , ProfessorLogin loggedinUser,CourseHistory c_history,Course cos,StudentLoginHistory history,studentLogin loggedInUser,EnrollmentHistory enrollmentList,Enrollment enroll) throws NullPointerException {
       
        initComponents();
        this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.loggedinUser = loggedinUser;
        this.history1 = history1;
        this.enroll = enroll;
        this.cos = cos;
        
        DisplayProfessorDetails();
        customizeComponents();
   
    }
    
    
    private void DisplayProfessorDetails(){
        txtFname.setText(loggedinUser.getFirstName());
        txtLname.setText(loggedinUser.getLastName());
        txtEmail.setText(loggedinUser.getEmail());
        txtUsername.setText(loggedinUser.getUsername());
        txtPassword.setText(loggedinUser.getPassword());
        
        String imagePathValue = loggedinUser.getImage();
        System.out.println(imagePathValue);
        ImageIcon ii = new ImageIcon(imagePathValue);
        Image image1 = ii.getImage();
        lblImage.setIcon(new ImageIcon(image1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassword = new javax.swing.JLabel();
        lblViewAccountTitle = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password : ");

        lblViewAccountTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblViewAccountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAccountTitle.setText("PROFESSOR ACCOUNT");

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("First Name :");

        txtFname.setEditable(false);

        txtLname.setEditable(false);

        lblLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLname.setText("Last Name :");
        lblLname.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email :");

        txtEmail.setEditable(false);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        txtUsername.setEditable(false);

        txtPassword.setEditable(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setAlignmentY(0.0F);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.setMaximumSize(new java.awt.Dimension(67, 18));
        lblImage.setMinimumSize(new java.awt.Dimension(67, 18));
        lblImage.setPreferredSize(new java.awt.Dimension(67, 18));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/female.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBack)
                .addGap(550, 550, 550)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblViewAccountTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFname)
                    .addComponent(txtLname)
                    .addComponent(txtEmail)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(575, 575, 575))
            .addGroup(layout.createSequentialGroup()
                .addGap(625, 625, 625)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblViewAccountTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        ViewProfessorPortalJPanel panel = new ViewProfessorPortalJPanel(workArea,history1,loggedinUser,c_history,cos,history,loggedInUser,enrollmentList,enroll);
        workArea.add("ViewProfessorPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    Font labelFont = new Font("Tahoma", Font.BOLD, 12);
    Color textColor = new Color(236, 240, 241);

    lblFname.setFont(labelFont);
    lblFname.setForeground(textColor);
    lblLname.setFont(labelFont);
    lblLname.setForeground(textColor);
    lblEmail.setFont(labelFont);
    lblEmail.setForeground(textColor);
    lblUsername.setFont(labelFont);
    lblUsername.setForeground(textColor);
    lblPassword.setFont(labelFont);
    lblPassword.setForeground(textColor);
    lblViewAccountTitle.setFont(new Font("Tahoma", Font.BOLD, 28));
    lblViewAccountTitle.setForeground(textColor);

    // Set text field and password field styles
    Color textFieldBackground = new Color(52, 73, 94);
    Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

    txtFname.setBackground(textFieldBackground);
    txtFname.setForeground(textColor);
    txtFname.setBorder(textFieldBorder);
    txtLname.setBackground(textFieldBackground);
    txtLname.setForeground(textColor);
    txtLname.setBorder(textFieldBorder);
    txtEmail.setBackground(textFieldBackground);
    txtEmail.setForeground(textColor);
    txtEmail.setBorder(textFieldBorder);
    txtUsername.setBackground(textFieldBackground);
    txtUsername.setForeground(textColor);
    txtUsername.setBorder(textFieldBorder);
    txtPassword.setBackground(textFieldBackground);
    txtPassword.setForeground(textColor);
    txtPassword.setBorder(textFieldBorder);

    // Set button style
    Color buttonBackground = new Color(52, 152, 219);
    Color buttonTextColor = new Color(255, 255, 255);
    Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

    btnBack.setBackground(buttonBackground);
    btnBack.setForeground(buttonTextColor);
    btnBack.setBorder(buttonBorder);

    // Set image label style
    lblImage.setBorder(BorderFactory.createLineBorder(new Color(236, 240, 241)));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblViewAccountTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
