/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Admin;

import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.EnrollmentHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author sanal
 */
public class AdminUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminUserAccountsJPanel
     */
    
    StudentLoginHistory history;
    javax.swing.JPanel workArea;
    studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    TicketManager ticketManager;
    CourseHistory chistory;
    
            
    public AdminUserAccountsJPanel(javax.swing.JPanel workArea, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList,TicketManager ticketManager,CourseHistory chistory) {
        
        initComponents();
        this.workArea = workArea;
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.ticketManager = ticketManager;
        txtPassword.setEditable(false);
        customizeComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btntblDelete = new javax.swing.JButton();
        btntblView = new javax.swing.JButton();
        lblUserinfo = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        txtSearchUsername = new javax.swing.JTextField();
        btntblSearch = new javax.swing.JButton();
        btnUpdateUserAccounts = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Email", "Username", "Password", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btntblDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btntblDelete.setText("Delete");
        btntblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntblDeleteActionPerformed(evt);
            }
        });

        btntblView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btntblView.setText("View");
        btntblView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntblViewActionPerformed(evt);
            }
        });

        lblUserinfo.setBackground(new java.awt.Color(204, 204, 255));
        lblUserinfo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblUserinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserinfo.setText("VIEW ALL USERS");

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("First Name :");

        lblLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLname.setText("Last Name :");
        lblLname.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email :");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password : ");

        txtSearchUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btntblSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btntblSearch.setText("Search By Username");
        btntblSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntblSearchActionPerformed(evt);
            }
        });

        btnUpdateUserAccounts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateUserAccounts.setText("Update");
        btnUpdateUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserAccountsActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/teamwork.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntblSearch)
                        .addGap(275, 275, 275)
                        .addComponent(btntblView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntblDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateUserAccounts)
                            .addComponent(txtFname)
                            .addComponent(txtLname)
                            .addComponent(txtEmail)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUserinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntblDelete)
                    .addComponent(btntblView)
                    .addComponent(btntblSearch)
                    .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnUpdateUserAccounts)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btntblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntblDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblUsers.getSelectedRow();

        if (selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

        String userType = model.getValueAt(selectedRowIndex, 5).toString();
        if ("Student".equals(userType)) {
            studentLogin selectedUser = (studentLogin) model.getValueAt(selectedRowIndex, 0);
            history.deleteStudent(selectedUser);
            JOptionPane.showMessageDialog(this, "Student Account Deleted.");
        } else if ("Professor".equals(userType)) {
            ProfessorLogin selectedProf = (ProfessorLogin) model.getValueAt(selectedRowIndex, 0);
            history1.deleteStudent(selectedProf);
            JOptionPane.showMessageDialog(this, "Professor Account Deleted.");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid user type.");
            return;
        }

        populateTable();


    }//GEN-LAST:event_btntblDeleteActionPerformed

    private void btntblViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntblViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblUsers.getSelectedRow();

        if (selectedRowIndex<0) {

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        //studentLogin selectedUser = (studentLogin) model.getValueAt(selectedRowIndex, 0);

        txtFname.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtLname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtEmail.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtUsername.setText(model.getValueAt(selectedRowIndex, 3).toString());
        String password = model.getValueAt(selectedRowIndex, 4).toString();
        String hashedPassword = hashPassword(password);
        txtPassword.setText(hashedPassword);


    }//GEN-LAST:event_btntblViewActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btntblSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntblSearchActionPerformed
        // TODO add your handling code here:

        String searchUsername = txtSearchUsername.getText().trim();
        populateTable(searchUsername);

    }//GEN-LAST:event_btntblSearchActionPerformed

    private void btnUpdateUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserAccountsActionPerformed
        // TODO add your handling code here:
        
        String firstName = txtFname.getText().trim();
        String lastName = txtLname.getText().trim();
        String email = txtEmail.getText().trim();
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        int selectedRowIndex = tblUsers.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a user to update.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        String userType = model.getValueAt(selectedRowIndex, 5).toString();

        if ("Student".equals(userType)) {
            studentLogin selectedUser = (studentLogin) model.getValueAt(selectedRowIndex, 0);
            selectedUser.setFirstName(firstName);
            selectedUser.setLastName(lastName);
            selectedUser.setEmail(email);
            selectedUser.setUsername(username);

        } else if ("Professor".equals(userType)) {
            ProfessorLogin selectedProf = (ProfessorLogin) model.getValueAt(selectedRowIndex, 0);
            selectedProf.setFirstName(firstName);
            selectedProf.setLastName(lastName);
            selectedProf.setEmail(email);
            selectedProf.setUsername(username);

        } else {
            JOptionPane.showMessageDialog(this, "Invalid user type.");
            return;
        }

        populateTable();
        JOptionPane.showMessageDialog(this, "User Updated Successfully.");
        
    }//GEN-LAST:event_btnUpdateUserAccountsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManageAdminJPanel panel = new ManageAdminJPanel(workArea,history,loggedInUser,loggedInProf,history1,enrollmentList,ticketManager,chistory);
        workArea.add("ManageAdminJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);
        
        
        for (studentLogin u : history.getHistory()){
            Object[] row = new Object[6];
            row[0] = u;
            row[1] = u.getLastName();
            row[2] = u.getEmail();
            row[3] = u.getUsername();
            row[4] = hashPassword(u.getPassword());
            row[5] = "Student";
            
            model.addRow(row);
        }
        
        for (ProfessorLogin p : history1.getHistory()){
            Object[] row = new Object[6];
            row[0] = p;
            row[1] = p.getLastName();
            row[2] = p.getEmail();
            row[3] = p.getUsername();
            row[4] = hashPassword(p.getPassword());
            row[5] = "Professor";

            
            model.addRow(row);
        }
    }
    
    private void populateTable(String filterUsername) {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);

        for (studentLogin u : history.getHistory()) {
            if (!filterUsername.isEmpty() && !u.getUsername().toLowerCase().contains(filterUsername.toLowerCase())) {
                continue;
            }
            Object[] row = new Object[6];
            row[0] = u;
            row[1] = u.getPassword();
            row[2] = u.getEmail();
            row[3] = u.getUsername();
            row[4] = u.getPassword();
            row[5] = "Student";

            model.addRow(row);
        }

        for (ProfessorLogin p : history1.getHistory()) {
            if (!filterUsername.isEmpty() && !p.getUsername().toLowerCase().contains(filterUsername.toLowerCase())) {
                continue;
            }
            Object[] row = new Object[6];
            row[0] = p;
            row[1] = p.getLastName();
            row[2] = p.getEmail();
            row[3] = p.getUsername();
            row[4] = p.getPassword();
            row[5] = "Professor";

            model.addRow(row);
        }
    }

    private String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes("UTF-8"));
            StringBuilder hexString = new StringBuilder();

            for (int i = 0; i < hash.length; i++) {
                String hex = Integer.toHexString(0xff & hash[i]);
                if(hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException | java.io.UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }
    
    private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    Font labelFont = new Font("Tahoma", Font.BOLD, 12);
    Color textColor = new Color(236, 240, 241);

    lblUserinfo.setFont(new Font("Tahoma", Font.BOLD, 28));
    lblUserinfo.setForeground(textColor);

    lblFname.setFont(labelFont);
    lblFname.setForeground(textColor);
    lblLname.setFont(labelFont);
    lblLname.setForeground(textColor);
    lblEmail.setFont(labelFont);
    lblEmail.setForeground(textColor);
    lblUsername.setFont(labelFont);
    lblUsername.setForeground(textColor);
    lblPassword.setFont(labelFont);
    lblPassword.setForeground(textColor);

    // Set text field and password field styles
    Color textFieldBackground = new Color(52, 73, 94);
    Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

    txtFname.setBackground(textFieldBackground);
    txtFname.setForeground(textColor);
    txtFname.setBorder(textFieldBorder);
    txtLname.setBackground(textFieldBackground);
    txtLname.setForeground(textColor);
    txtLname.setBorder(textFieldBorder);
    txtEmail.setBackground(textFieldBackground);
    txtEmail.setForeground(textColor);
    txtEmail.setBorder(textFieldBorder);
    txtUsername.setBackground(textFieldBackground);
    txtUsername.setForeground(textColor);
    txtUsername.setBorder(textFieldBorder);
    txtPassword.setBackground(textFieldBackground);
    txtPassword.setForeground(textColor);
    txtPassword.setBorder(textFieldBorder);
    txtSearchUsername.setBackground(textFieldBackground);
    txtSearchUsername.setForeground(textColor);
    txtSearchUsername.setBorder(textFieldBorder);

    // Set button style
    Color buttonBackground = new Color(52, 152, 219);
    Color buttonTextColor = new Color(255, 255, 255);
    Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

    btntblDelete.setBackground(buttonBackground);
    btntblDelete.setForeground(buttonTextColor);
    btntblDelete.setBorder(buttonBorder);
    btntblView.setBackground(buttonBackground);
    btntblView.setForeground(buttonTextColor);
    btntblView.setBorder(buttonBorder);
    btntblSearch.setBackground(buttonBackground);
    btntblSearch.setForeground(buttonTextColor);
    btntblSearch.setBorder(buttonBorder);
    btnUpdateUserAccounts.setBackground(buttonBackground);
    btnUpdateUserAccounts.setForeground(buttonTextColor);
    btnUpdateUserAccounts.setBorder(buttonBorder);
    btnBack.setBackground(buttonBackground);
    btnBack.setForeground(buttonTextColor);
    btnBack.setBorder(buttonBorder);

    // Set table style
    tblUsers.setBackground(textFieldBackground);
    tblUsers.setForeground(textColor);
    tblUsers.setFont(new Font("Tahoma", Font.PLAIN, 14));
    jScrollPane1.getViewport().setBackground(new Color(44, 62, 80));
    
    // Set table header style
    tblUsers.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
    tblUsers.getTableHeader().setBackground(new Color(52, 73, 94));
    tblUsers.getTableHeader().setForeground(new Color(44, 62, 80));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateUserAccounts;
    private javax.swing.JButton btntblDelete;
    private javax.swing.JButton btntblSearch;
    private javax.swing.JButton btntblView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserinfo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearchUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
