/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Admin;
//package Business;

import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;

/**
 *
 * @author anzal
 */
public class AdminLoginPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginPageJPanel
     */
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    TicketManager ticketManager;
    CourseHistory chistory;

    public AdminLoginPageJPanel(javax.swing.JPanel workArea, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList, TicketManager ticketManager,CourseHistory chistory) {
    
        this.workArea = workArea;
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.ticketManager = ticketManager;
        this.chistory = chistory;
        initComponents();
        customizeComponents();
        
        
        
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleAdminLogin = new javax.swing.JLabel();
        lblAdminUsername = new javax.swing.JLabel();
        lblAdminPass = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        txtAdminPass = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();
        lblAdminImage = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));

        lblTitleAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleAdminLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAdminLogin.setText("ADMIN LOGIN");

        lblAdminUsername.setText("Username :");

        lblAdminPass.setText("Password : ");

        btnAdminLogin.setText("Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        lblAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/login-ext.png"))); // NOI18N
        lblAdminImage.setMaximumSize(new java.awt.Dimension(2308, 2002));
        lblAdminImage.setMinimumSize(new java.awt.Dimension(2308, 2002));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleAdminLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdminPass)
                                .addGap(18, 18, 18)
                                .addComponent(txtAdminPass))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdminUsername)
                                .addGap(18, 18, 18)
                                .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblTitleAdminLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminUsername)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPass)
                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAdminLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        
        
        String username = txtAdminUsername.getText();
        String username_predefined = "admin";
        String password = String.valueOf(txtAdminPass.getPassword());
        String password_predefined = "admin";
       

      
        if(username.equals(username_predefined) && (password.equals(password_predefined))){
            
            JOptionPane.showMessageDialog(this, "Succcessfully logged in");
          
       txtAdminUsername.setText(null);
       txtAdminPass.setText(null);
       
        ManageAdminJPanel panel = new ManageAdminJPanel(workArea,history,loggedInUser,loggedInProf,history1,enrollmentList,ticketManager,chistory);
        workArea.add("ManageAdminJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
       
      
        }
        else{
            JOptionPane.showMessageDialog(this, "Wrong Username or Password ", "Error", JOptionPane.ERROR_MESSAGE);
             }
        
        
        
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void customizeComponents() {
        
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        lblTitleAdminLogin.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblTitleAdminLogin.setForeground(new Color(236, 240, 241));
        lblAdminUsername.setForeground(new Color(236, 240, 241));
        lblAdminPass.setForeground(new Color(236, 240, 241));

        // Set text field and password field styles
        txtAdminUsername.setBackground(new Color(52, 73, 94));
        txtAdminUsername.setForeground(new Color(236, 240, 241));
        txtAdminUsername.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        txtAdminPass.setBackground(new Color(52, 73, 94));
        txtAdminPass.setForeground(new Color(236, 240, 241));
        txtAdminPass.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));

        // Set button style
        btnAdminLogin.setBackground(new Color(52, 152, 219));
        btnAdminLogin.setForeground(new Color(255, 255, 255));
        btnAdminLogin.setBorder(BorderFactory.createEmptyBorder(10, 25, 10, 25));

        /*
        // Adjust layout and padding
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitleAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminUsername)
                            .addComponent(lblAdminPass))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminUsername)
                            .addComponent(txtAdminPass, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(btnAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitleAdminLogin)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminUsername)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPass)
                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAdminLogin)
                .addContainerGap(50, Short.MAX_VALUE))
                
        );
        */
        
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JLabel lblAdminImage;
    private javax.swing.JLabel lblAdminPass;
    private javax.swing.JLabel lblAdminUsername;
    private javax.swing.JLabel lblTitleAdminLogin;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JTextField txtAdminUsername;
    // End of variables declaration//GEN-END:variables
}
