/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Admin;

import Business.Professor.Course;
import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.EnrollmentHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author sanal
 */
public class AdminPerformanceJPanel extends javax.swing.JPanel {

    StudentLoginHistory history;
    javax.swing.JPanel workArea;
    studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    TicketManager ticketManager;
    CourseHistory chistory;
    
    /**
     * Creates new form AdminPerformanceJPanel
     */
    public AdminPerformanceJPanel(javax.swing.JPanel workArea, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList,TicketManager ticketManager, CourseHistory chistory) {
        initComponents();
        this.workArea = workArea;
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.ticketManager = ticketManager;
        this.chistory = chistory;
        customizeComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserinfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblRegActivity = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblUserinfo.setBackground(new java.awt.Color(204, 204, 255));
        lblUserinfo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblUserinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserinfo.setText("PERFORMANCE");

        tblUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Username", "Role", "Registered Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        lblRegActivity.setBackground(new java.awt.Color(204, 204, 255));
        lblRegActivity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegActivity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegActivity.setText("Registration Activity");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/pie-chart.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUserinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserinfo)
                .addGap(27, 27, 27)
                .addComponent(lblRegActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManageAdminJPanel panel = new ManageAdminJPanel(workArea,history,loggedInUser,loggedInProf,history1,enrollmentList,ticketManager,chistory);
        workArea.add("ManageAdminJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
    model.setRowCount(0);

    for (studentLogin u : history.getHistory()){
        Object[] row = new Object[6];
        row[0] = u;
        row[1] = u.getLastName();
        row[2] = u.getUsername();
        row[3] = "Student";
        row[4] = u.getTimestamp(); // add this line
        model.addRow(row);
    }

    for (ProfessorLogin p : history1.getHistory()){
        Object[] row = new Object[6];
        row[0] = p;
        row[1] = p.getLastName();
        row[2] = p.getUsername();
        row[3] = "Professor";
        row[4] = p.getTimestamp(); // add this line
        model.addRow(row);
    }
    
    
    }
    
    private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    lblUserinfo.setFont(new Font("Tahoma", Font.BOLD, 28));
    lblUserinfo.setForeground(new Color(236, 240, 241));
    lblRegActivity.setForeground(new Color(236, 240, 241));

    // Set table styles
    tblUsers.setBackground(new Color(52, 73, 94));
    tblUsers.setForeground(new Color(236, 240, 241));
    tblUsers.getTableHeader().setBackground(new Color(52, 73, 94));
    tblUsers.getTableHeader().setForeground(new Color(44, 62, 80));
    tblUsers.setFont(new Font("Tahoma", Font.BOLD, 14));
    

    // Set scroll pane styles
    jScrollPane1.getViewport().setBackground(new Color(52, 73, 94));
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegActivity;
    private javax.swing.JLabel lblUserinfo;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
