/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Admin;

import Business.Admin.AdminUserAccountsJPanel;
import Business.Student.StudentLoginHistory;
import Business.Student.studentLogin;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author anzal
 */
public class ManageAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdminJPanel
     */

    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    TicketManager ticketManager;
    CourseHistory chistory;
    
    

    
   public ManageAdminJPanel(JPanel workArea, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList, TicketManager ticketManager, CourseHistory chistory) {
        initComponents();
        this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.ticketManager = ticketManager;
        this.chistory = chistory;
        
        btnAdminCreateTickets.setVisible(false);
        btnViewTicketStudent.setVisible(false);
        
        // Customize components
        customizeComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminAccounts = new javax.swing.JButton();
        btnAdminManageStudents = new javax.swing.JButton();
        btnAdminManageProfessors = new javax.swing.JButton();
        btnAdminViewTickets = new javax.swing.JButton();
        btnAdminCreateTickets = new javax.swing.JButton();
        btnViewTicketStudent = new javax.swing.JButton();
        lblTitleAdminLogin = new javax.swing.JLabel();
        lblAdminPanelImage = new javax.swing.JLabel();
        btnAdminPerformance = new javax.swing.JButton();

        btnAdminAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/admin.png"))); // NOI18N
        btnAdminAccounts.setText("Administer User Accounts");
        btnAdminAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAccountsActionPerformed(evt);
            }
        });

        btnAdminManageStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/graduated.png"))); // NOI18N
        btnAdminManageStudents.setText("Manage Students");
        btnAdminManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminManageStudentsActionPerformed(evt);
            }
        });

        btnAdminManageProfessors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/teacher.png"))); // NOI18N
        btnAdminManageProfessors.setText("Manage Professors");
        btnAdminManageProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminManageProfessorsActionPerformed(evt);
            }
        });

        btnAdminViewTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/support-ticket.png"))); // NOI18N
        btnAdminViewTickets.setText("View Tickets");
        btnAdminViewTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminViewTicketsActionPerformed(evt);
            }
        });

        btnAdminCreateTickets.setText("Create Tickets");
        btnAdminCreateTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCreateTicketsActionPerformed(evt);
            }
        });

        btnViewTicketStudent.setText("View Student Ticket");
        btnViewTicketStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTicketStudentActionPerformed(evt);
            }
        });

        lblTitleAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleAdminLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAdminLogin.setText("ADMIN PANEL");

        lblAdminPanelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/software-engineer.png"))); // NOI18N

        btnAdminPerformance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/stats.png"))); // NOI18N
        btnAdminPerformance.setText("Performance");
        btnAdminPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminPerformanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewTicketStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminViewTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminCreateTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAdminPanelImage)
                        .addGap(581, 581, 581))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminManageStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminManageProfessors, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminAccounts, btnAdminManageProfessors, btnAdminManageStudents, btnAdminViewTickets});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblTitleAdminLogin)
                .addGap(31, 31, 31)
                .addComponent(lblAdminPanelImage)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminAccounts)
                    .addComponent(btnAdminManageProfessors)
                    .addComponent(btnAdminManageStudents))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminViewTickets)
                    .addComponent(btnAdminPerformance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminCreateTickets)
                    .addComponent(btnViewTicketStudent))
                .addContainerGap(364, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdminAccounts, btnAdminManageProfessors, btnAdminManageStudents, btnAdminViewTickets});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAccountsActionPerformed
        // TODO add your handling code here:
        
        AdminUserAccountsJPanel panel = new AdminUserAccountsJPanel(workArea, history, loggedInUser, loggedInProf, history1, enrollmentList,ticketManager,chistory);
        workArea.add("AdminUserAccountsJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminAccountsActionPerformed
    
    private void btnAdminManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminManageStudentsActionPerformed
        // TODO add your handling code here:
        AdminStudentControlJPanel panel = new AdminStudentControlJPanel(workArea, history, loggedInUser, history1, loggedInProf, enrollmentList,ticketManager,chistory);
        workArea.add("AdminStudentControlJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminManageStudentsActionPerformed

    private void btnAdminManageProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminManageProfessorsActionPerformed
        // TODO add your handling code here:
        AdminProfessorControlJPanel panel = new AdminProfessorControlJPanel(workArea, loggedInUser, history, history1, loggedInProf, enrollmentList,ticketManager,chistory);
        workArea.add("AdminProfessorControlJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminManageProfessorsActionPerformed

    private void btnAdminViewTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminViewTicketsActionPerformed
        // TODO add your handling code here:
        TicketManager ticketManager = TicketManager.getInstance();
        ViewTicketAdminJPanel panel = new ViewTicketAdminJPanel(workArea, ticketManager, history, loggedInUser, loggedInProf, history1, enrollmentList,chistory);
        workArea.add("ViewTicketAdminJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminViewTicketsActionPerformed

    private void btnAdminPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPerformanceActionPerformed
        // TODO add your handling code here:
        AdminPerformanceJPanel panel = new AdminPerformanceJPanel(workArea, history, loggedInUser, loggedInProf, history1, enrollmentList,ticketManager,chistory);
        workArea.add("AdminPerformanceJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminPerformanceActionPerformed

    private void btnAdminCreateTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCreateTicketsActionPerformed
        // TODO add your handling code here:
        CreateTicketJPanel panel = new CreateTicketJPanel(workArea, history, loggedInUser, loggedInProf, history1, enrollmentList,chistory);
        workArea.add("AdminCreateTicketJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdminCreateTicketsActionPerformed

    private void btnViewTicketStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTicketStudentActionPerformed
        // TODO add your handling code here:
        ViewTicketSingleJPanel panel = new ViewTicketSingleJPanel(workArea, ticketManager, history, loggedInUser, loggedInProf, history1, enrollmentList,chistory);
        workArea.add("ViewTicketStudentJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewTicketStudentActionPerformed

    private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        lblTitleAdminLogin.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblTitleAdminLogin.setForeground(new Color(236, 240, 241));

        // Set button styles
        customizeButton(btnAdminAccounts);
        customizeButton(btnAdminManageStudents);
        customizeButton(btnAdminManageProfessors);
        customizeButton(btnAdminViewTickets);
        customizeButton(btnAdminPerformance);
        customizeButton(btnAdminCreateTickets);
        customizeButton(btnViewTicketStudent);
        
    }

    private void customizeButton(javax.swing.JButton button) {
        button.setBackground(new Color(52, 152, 219));
        button.setForeground(new Color(255, 255, 255));
        button.setBorder(BorderFactory.createEmptyBorder(10, 25, 10, 25));
        button.setFont(new Font("Tahoma", Font.BOLD, 12));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminAccounts;
    private javax.swing.JButton btnAdminCreateTickets;
    private javax.swing.JButton btnAdminManageProfessors;
    private javax.swing.JButton btnAdminManageStudents;
    private javax.swing.JButton btnAdminPerformance;
    private javax.swing.JButton btnAdminViewTickets;
    private javax.swing.JButton btnViewTicketStudent;
    private javax.swing.JLabel lblAdminPanelImage;
    private javax.swing.JLabel lblTitleAdminLogin;
    // End of variables declaration//GEN-END:variables
}
