/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Student;

import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author zakir
 */
public class ManageStudentAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentAccountJPanel
     */
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    private ProfessorLogin profLogin;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    TicketManager ticketManager;
    
    public ManageStudentAccountJPanel(JPanel workArea, StudentLoginHistory history,studentLogin loggedInUser, EnrollmentHistory enrollmentList,CourseHistory c_history,ProfessorLogin profLogin,ProfessorLoginHistory history1,Enrollment enroll,TicketManager ticketManager) {
        initComponents();
        this.workArea = workArea;
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.profLogin = profLogin;
        this.history1 = history1;
        this.enroll = enroll;
        this.ticketManager = ticketManager;
        
        DisplayStudentsData();
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblNeu = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblPincode = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtNeu = new javax.swing.JTextField();
        lblManageAccount = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLname.setText("Last Name :");
        lblLname.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username : ");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblNeu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNeu.setText("NEU ID :");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age : ");

        lblPincode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPincode.setText("Pincode : ");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress.setText("Address : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email : ");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setText("Phone : ");

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("First Name :");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password : ");

        lblManageAccount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblManageAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageAccount.setText("MANAGE ACCOUNT");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/graduates.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname)
                            .addComponent(txtLname)
                            .addComponent(txtNeu)
                            .addComponent(txtAge)
                            .addComponent(txtEmail)
                            .addComponent(txtPhone)
                            .addComponent(txtPincode)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(328, 328, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(575, 575, 575))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblManageAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNeu)
                    .addComponent(txtNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPincode)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String firstName = txtFname.getText();
        String lastName = txtLname.getText();
        int neuId = Integer.parseInt(txtNeu.getText());
        int age = Integer.parseInt(txtAge.getText());
        String email = txtEmail.getText();
        int phone = Integer.parseInt(txtPhone.getText());
        int pincode = Integer.parseInt(txtPincode.getText());
        String address = txtAddress.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        studentLogin updatedProfile = new studentLogin();
        updatedProfile.setFirstName(firstName);
        updatedProfile.setLastName(lastName);
        updatedProfile.setNeuId(neuId);
        updatedProfile.setAge(age);
        updatedProfile.setEmail(email);
        updatedProfile.setPhone(phone);
        updatedProfile.setPincode(pincode);
        updatedProfile.setAddress(address);
        updatedProfile.setUsername(username);
        updatedProfile.setPassword(password);
        
        ArrayList<studentLogin> students = history.getHistory();
        
        for(studentLogin updatedStudents : students ){
        updatedStudents.setFirstName(firstName);
        updatedStudents.setLastName(lastName);
        updatedStudents.setNeuId(neuId);
        updatedStudents.setAge(age);
        updatedStudents.setEmail(email);
        updatedStudents.setPhone(phone);
        updatedStudents.setPincode(pincode);
        updatedStudents.setAddress(address);
        updatedStudents.setUsername(username);
        updatedStudents.setPassword(password);
        break;
        }
        
        
        JOptionPane.showMessageDialog(this, "Profile updated Successfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewStudentPortalJPanel panel = new ViewStudentPortalJPanel(workArea,history,loggedInUser,enrollmentList,c_history,profLogin,history1,enroll,ticketManager);
        workArea.add("ViewStudentPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblManageAccount;
    private javax.swing.JLabel lblNeu;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPincode;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNeu;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void DisplayStudentsData() {
        txtFname.setText(loggedInUser.getFirstName());
        txtLname.setText(loggedInUser.getLastName());
        txtNeu.setText(String.valueOf(loggedInUser.getNeuId()));
        txtAge.setText(String.valueOf(loggedInUser.getAge()));
        txtEmail.setText(loggedInUser.getEmail());
        txtPhone.setText(String.valueOf(loggedInUser.getPhone()));
        txtPincode.setText(String.valueOf(loggedInUser.getPincode()));
        txtAddress.setText(loggedInUser.getAddress());
        txtUsername.setText(loggedInUser.getUsername());
        txtPassword.setText(loggedInUser.getPassword()); 
    }

   private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        Font labelFont = new Font("Tahoma", Font.BOLD, 12);
        Color textColor = new Color(236, 240, 241);

        lblManageAccount.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblManageAccount.setForeground(textColor);

        lblFname.setFont(labelFont);
        lblFname.setForeground(textColor);
        lblLname.setFont(labelFont);
        lblLname.setForeground(textColor);
        lblNeu.setFont(labelFont);
        lblNeu.setForeground(textColor);
        lblAge.setFont(labelFont);
        lblAge.setForeground(textColor);
        lblEmail.setFont(labelFont);
        lblEmail.setForeground(textColor);
        lblPhone.setFont(labelFont);
        lblPhone.setForeground(textColor);
        lblPincode.setFont(labelFont);
        lblPincode.setForeground(textColor);
        lblAddress.setFont(labelFont);
        lblAddress.setForeground(textColor);
        lblUsername.setFont(labelFont);
        lblUsername.setForeground(textColor);
        lblPassword.setFont(labelFont);
        lblPassword.setForeground(textColor);

        // Set text field and password field styles
        Color textFieldBackground = new Color(52, 73, 94);
        Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

        txtFname.setBackground(textFieldBackground);
        txtFname.setForeground(textColor);
        txtFname.setBorder(textFieldBorder);
        txtLname.setBackground(textFieldBackground);
        txtLname.setForeground(textColor);
        txtLname.setBorder(textFieldBorder);
        txtNeu.setBackground(textFieldBackground);
        txtNeu.setForeground(textColor);
        txtNeu.setBorder(textFieldBorder);
        txtAge.setBackground(textFieldBackground);
        txtAge.setForeground(textColor);
        txtAge.setBorder(textFieldBorder);
        txtEmail.setBackground(textFieldBackground);
        txtEmail.setForeground(textColor);
        txtEmail.setBorder(textFieldBorder);
        txtPhone.setBackground(textFieldBackground);
        txtPhone.setForeground(textColor);
        txtPhone.setBorder(textFieldBorder);
        txtPincode.setBackground(textFieldBackground);
        txtPincode.setForeground(textColor);
        txtPincode.setBorder(textFieldBorder);
        txtAddress.setBackground(textFieldBackground);
        txtAddress.setForeground(textColor);
        txtAddress.setBorder(textFieldBorder);
        txtUsername.setBackground(textFieldBackground);
        txtUsername.setForeground(textColor);
        txtUsername.setBorder(textFieldBorder);
        txtPassword.setBackground(textFieldBackground);
        txtPassword.setForeground(textColor);
        txtPassword.setBorder(textFieldBorder);

        // Set button style
        Color buttonBackground = new Color(52, 152, 219);
        Color buttonTextColor = new Color(255, 255, 255);
        Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

        btnUpdate.setBackground(buttonBackground);
        btnUpdate.setForeground(buttonTextColor);
        btnUpdate.setBorder(buttonBorder);
        btnBack.setBackground(buttonBackground);
        btnBack.setForeground(buttonTextColor);
        btnBack.setBorder(buttonBorder);
    }

}
