/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Student;

import Business.Admin.*;
import Business.Student.Enrollment;
import Business.Student.*;
import Business.Admin.Ticket;
import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import javax.swing.JOptionPane;
import java.util.Random;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.EnrollmentHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


/**
 *
 * @author sanal
 */
public class StudentCreateTicketJPanel extends javax.swing.JPanel {
    
    private TicketManager ticketManager;
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    CourseHistory chistory;
    Enrollment enroll;
    
    /**
     * Creates new form StudentTicketJPanel
     */
    public StudentCreateTicketJPanel(javax.swing.JPanel workArea, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList,CourseHistory chistory,Enrollment enroll) {
        initComponents();
        this.workArea = workArea;
        this.ticketManager = TicketManager.getInstance(); // Fetch the singleton instance
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.chistory = chistory;
        this.enroll = enroll;
        customizeComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnRaiseTicket = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTicket = new javax.swing.JTextArea();
        lblTicketName = new javax.swing.JLabel();
        txtTicketName = new javax.swing.JTextField();
        lblTypeIssue = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("RAISE A TICKET");

        btnRaiseTicket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRaiseTicket.setText("Raise Ticket");
        btnRaiseTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseTicketActionPerformed(evt);
            }
        });

        TextAreaTicket.setColumns(20);
        TextAreaTicket.setRows(5);
        jScrollPane1.setViewportView(TextAreaTicket);

        lblTicketName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTicketName.setText("Name:");

        lblTypeIssue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTypeIssue.setText("Type Your Issue:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/support-ticket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTypeIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTicketName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTicketName, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)
                        .addGap(253, 253, 253)
                        .addComponent(btnRaiseTicket)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketName)
                    .addComponent(txtTicketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTypeIssue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaiseTicket)
                    .addComponent(btnBack))
                .addGap(300, 300, 300))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaiseTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseTicketActionPerformed
        // TODO add your handling code here:
        String message = TextAreaTicket.getText().trim();
        String ticketName = txtTicketName.getText().trim();

        if (!message.isEmpty() && !ticketName.isEmpty()) {
            Random rand = new Random();
            int randomNumber;
            do {
                randomNumber = 100 + rand.nextInt(900); // Generates a number between 100 and 999
            } while (ticketManager.isRandomNumberTaken(randomNumber));

            String ticketId = String.valueOf(randomNumber);
            Ticket newTicket = new Ticket(ticketName, message, ticketId);
            ticketManager.addTicket(newTicket);

            TextAreaTicket.setText("");
            txtTicketName.setText("");
            JOptionPane.showMessageDialog(this, "Successfully raised ticket. Your unique number is: " + ticketId);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter both ticket name and message.");
        }
        
    }//GEN-LAST:event_btnRaiseTicketActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewStudentPortalJPanel panel = new ViewStudentPortalJPanel(workArea,history,loggedInUser,enrollmentList,chistory,loggedInProf,history1,enroll,ticketManager);
        workArea.add("ViewStudentPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels and title
        Font labelFont = new Font("Tahoma", Font.BOLD, 12);
        Color textColor = new Color(236, 240, 241);
        lblTitle.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblTitle.setForeground(textColor);
        lblTicketName.setFont(labelFont);
        lblTicketName.setForeground(textColor);
        lblTypeIssue.setFont(labelFont);
        lblTypeIssue.setForeground(textColor);

        // Set text field styles
        Color textFieldBackground = new Color(52, 73, 94);
        Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);
        txtTicketName.setBackground(textFieldBackground);
        txtTicketName.setForeground(textColor);
        txtTicketName.setBorder(textFieldBorder);

        // Set text area styles
        TextAreaTicket.setBackground(textFieldBackground);
        TextAreaTicket.setForeground(textColor);
        TextAreaTicket.setBorder(textFieldBorder);
        jScrollPane1.getViewport().setBackground(new Color(44, 62, 80));

        // Set button style
        Color buttonBackground = new Color(52, 152, 219);
        Color buttonTextColor = new Color(255, 255, 255);
        Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);
        btnRaiseTicket.setBackground(buttonBackground);
        btnRaiseTicket.setForeground(buttonTextColor);
        btnRaiseTicket.setBorder(buttonBorder);
        btnBack.setBackground(buttonBackground);
        btnBack.setForeground(buttonTextColor);
        btnBack.setBorder(buttonBorder);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaTicket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRaiseTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTicketName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeIssue;
    private javax.swing.JTextField txtTicketName;
    // End of variables declaration//GEN-END:variables
}
