/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Student;

import Business.Admin.ManageAdminJPanel;
import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author anzal
 */
public class StudentLoginPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentLoginPageJPanel
     */
    
    StudentLoginHistory history;
    javax.swing.JPanel workArea;
    private studentLogin loggedInUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    private ProfessorLogin profLogin;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    TicketManager ticketManager;
            
    public StudentLoginPageJPanel(JPanel workArea,StudentLoginHistory history,studentLogin loggedInUser,EnrollmentHistory enrollmentList,CourseHistory c_history,ProfessorLogin profLogin,ProfessorLoginHistory history1,Enrollment enroll,TicketManager ticketManager) {
       initComponents();
       this.history = history;
       this.loggedInUser = loggedInUser;
       this.workArea = workArea;
       this.enrollmentList = enrollmentList;
       this.c_history = c_history;
       this.profLogin = profLogin;
       this.history1 = history1;
       this.enroll = enroll;
       this.ticketManager = ticketManager;
       customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleStudentLogin = new javax.swing.JLabel();
        lblStudUsername = new javax.swing.JLabel();
        lblStudPass = new javax.swing.JLabel();
        txtStudUsername = new javax.swing.JTextField();
        txtStudPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblAdminImage = new javax.swing.JLabel();

        lblTitleStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitleStudentLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleStudentLogin.setText("STUDENT LOGIN PAGE");

        lblStudUsername.setText("Username :");

        lblStudPass.setText("Password : ");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/login-ext.png"))); // NOI18N
        lblAdminImage.setMaximumSize(new java.awt.Dimension(2308, 2002));
        lblAdminImage.setMinimumSize(new java.awt.Dimension(2308, 2002));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleStudentLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudPass)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtStudPass))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudUsername)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtStudUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(66, 66, 66)))))
                .addGap(565, 565, 565))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblTitleStudentLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudUsername)
                    .addComponent(txtStudUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudPass)
                    .addComponent(txtStudPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (txtStudUsername.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter the username");
            } else if (txtStudPass.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Please enter the password");
            } else {
            String enteredUsername = txtStudUsername.getText();
            String enteredPassword = new String(txtStudPass.getPassword());
            
            
            // Verify credentials with data in history ArrayList
            boolean credentialsMatch = false;
            
            for (studentLogin user : history.getHistory()) {
            if (user.getUsername().equals(enteredUsername) && user.getPassword().equals(enteredPassword)) {
                credentialsMatch = true;
                break;
            } 
        }
            
             if (credentialsMatch) {
                JOptionPane.showMessageDialog(null, "Login Successful");

                studentLogin loggedInUser = null;
                    for (studentLogin user : history.getHistory()) {
                if (user.getUsername().equals(enteredUsername) && user.getPassword().equals(enteredPassword)) {
                    loggedInUser = user;
                    break;
            }
        }
                    if (loggedInUser != null) {
                        ViewStudentPortalJPanel panel = new ViewStudentPortalJPanel(workArea,history,loggedInUser,enrollmentList,c_history,profLogin,history1,enroll,ticketManager);
                        workArea.add("ViewStudentPortalJPanel", panel);
                        CardLayout layout = (CardLayout) workArea.getLayout();
                        layout.next(workArea);
                    }else{
            JOptionPane.showMessageDialog(null, "User not found!", "Message", JOptionPane.ERROR_MESSAGE);
        }
                    
             }
             else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!", "Message", JOptionPane.ERROR_MESSAGE);
            }}
    }//GEN-LAST:event_btnLoginActionPerformed


    private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    Font labelFont = new Font("Tahoma", Font.BOLD, 12);
    Color textColor = new Color(236, 240, 241);

    lblTitleStudentLogin.setFont(new Font("Tahoma", Font.BOLD, 28));
    lblTitleStudentLogin.setForeground(textColor);

    lblStudUsername.setFont(labelFont);
    lblStudUsername.setForeground(textColor);
    lblStudPass.setFont(labelFont);
    lblStudPass.setForeground(textColor);

    // Set text field and password field styles
    Color textFieldBackground = new Color(52, 73, 94);
    Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

    txtStudUsername.setBackground(textFieldBackground);
    txtStudUsername.setForeground(textColor);
    txtStudUsername.setBorder(textFieldBorder);
    txtStudPass.setBackground(textFieldBackground);
    txtStudPass.setForeground(textColor);
    txtStudPass.setBorder(textFieldBorder);

    // Set button style
    Color buttonBackground = new Color(52, 152, 219);
    Color buttonTextColor = new Color(255, 255, 255);
    Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

    btnLogin.setBackground(buttonBackground);
    btnLogin.setForeground(buttonTextColor);
    btnLogin.setBorder(buttonBorder);
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblAdminImage;
    private javax.swing.JLabel lblStudPass;
    private javax.swing.JLabel lblStudUsername;
    private javax.swing.JLabel lblTitleStudentLogin;
    private javax.swing.JPasswordField txtStudPass;
    private javax.swing.JTextField txtStudUsername;
    // End of variables declaration//GEN-END:variables
}
