/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Student;

import Business.Admin.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Student.*;
import Business.Admin.Ticket;
import Business.Admin.TicketManager;
import Business.Professor.CourseHistory;
import javax.swing.JOptionPane;
import java.util.Random;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Student.EnrollmentHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author sanal
 */
public class StudentViewTicketJPanel extends javax.swing.JPanel {
    
    private TicketManager ticketManager;
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    studentLogin loggedInUser;
    ProfessorLogin loggedInProf;
    ProfessorLoginHistory history1;
    EnrollmentHistory enrollmentList;
    CourseHistory chistory;
    Enrollment enroll;

    /**
     * Creates new form ViewTicketJPanel
     */
    public StudentViewTicketJPanel(javax.swing.JPanel workArea, TicketManager ticketManager, StudentLoginHistory history, studentLogin loggedInUser, ProfessorLogin loggedInProf, ProfessorLoginHistory history1, EnrollmentHistory enrollmentList,CourseHistory chistory, Enrollment enroll) {
        this.ticketManager = ticketManager;
        this.workArea = workArea;
        this.history = history;
        this.loggedInUser = loggedInUser;
        this.loggedInProf = loggedInProf;
        this.history1 = history1;
        this.enrollmentList = enrollmentList;
        this.chistory = chistory;
        this.enroll = enroll;

        initComponents();  // Initialize components before manipulating them

        setTicketInfoVisibility(false);  // Now safe to call this method

        txtName.setEditable(false);
        txtTicket.setEditable(false);
        txtTicketID.setEditable(false);
        txtResolved.setEditable(false);
        txtComment.setEditable(false);
        
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblViewTickets = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        btnSearchTicketID = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtTicket = new javax.swing.JTextField();
        lblTicket = new javax.swing.JLabel();
        lblTicketID = new javax.swing.JLabel();
        txtTicketID = new javax.swing.JTextField();
        txtSearchTicketID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtResolved = new javax.swing.JTextField();
        lblComment = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Resolved:");

        lblViewTickets.setBackground(new java.awt.Color(204, 204, 255));
        lblViewTickets.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblViewTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/support-ticket.png"))); // NOI18N
        lblViewTickets.setText("View Tickets");

        lblFname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFname.setText("Name:");

        btnSearchTicketID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchTicketID.setText("Search Ticket ID");
        btnSearchTicketID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTicketIDActionPerformed(evt);
            }
        });

        txtTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketActionPerformed(evt);
            }
        });

        lblTicket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTicket.setText("Ticket:");
        lblTicket.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblTicketID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTicketID.setText("Ticket ID:");

        txtSearchTicketID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblComment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComment.setText("Comment:");
        lblComment.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSearchTicketID))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblComment, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtResolved, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTicketID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(610, 610, 610))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblViewTickets)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchTicketID))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketID)
                    .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtResolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTicket)
                    .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComment)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchTicketIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTicketIDActionPerformed
        // TODO add your handling code here:
        
        String ticketID = txtSearchTicketID.getText();
        Ticket ticket = ticketManager.getTicketById(ticketID);
        if (ticket != null) {
            System.out.println("Comment from Ticket: " + ticket.getComment());
            System.out.println("Name from Ticket: " + ticket.getName());
            txtName.setText(ticket.getName());
            txtTicketID.setText(ticket.getTicketId());
            txtResolved.setText(ticket.isResolved() ? "Yes" : "No");
            txtTicket.setText(ticket.getMessage());
            txtComment.setText(ticket.getComment());
            setTicketInfoVisibility(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ticket not found!");
            setTicketInfoVisibility(false);
        }

        
    }//GEN-LAST:event_btnSearchTicketIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewStudentPortalJPanel panel = new ViewStudentPortalJPanel(workArea,history,loggedInUser,enrollmentList,chistory,loggedInProf,history1,enroll,ticketManager);
        workArea.add("ViewStudentPortalJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketActionPerformed

    private void setTicketInfoVisibility(boolean visible) {
    lblFname.setVisible(visible);
    lblTicketID.setVisible(visible);
    lblUsername.setVisible(visible);
    lblTicket.setVisible(visible);
    lblComment.setVisible(visible);
    
    txtName.setVisible(visible);
    txtTicketID.setVisible(visible);
    txtResolved.setVisible(visible);
    txtTicket.setVisible(visible);
    txtComment.setVisible(visible);
}
    private void customizeComponents() {
        // Set background color
        this.setBackground(new Color(44, 62, 80));

        // Set font and text color for labels
        Font labelFont = new Font("Tahoma", Font.BOLD, 12);
        Color textColor = new Color(236, 240, 241);

        lblViewTickets.setFont(new Font("Tahoma", Font.BOLD, 28));
        lblViewTickets.setForeground(textColor);

        lblFname.setFont(labelFont);
        lblFname.setForeground(textColor);
        lblTicket.setFont(labelFont);
        lblTicket.setForeground(textColor);
        lblTicketID.setFont(labelFont);
        lblTicketID.setForeground(textColor);
        lblUsername.setFont(labelFont);
        lblUsername.setForeground(textColor);
        lblComment.setFont(labelFont);
        lblComment.setForeground(textColor);

        // Set text field styles
        Color textFieldBackground = new Color(52, 73, 94);
        Border textFieldBorder = BorderFactory.createEmptyBorder(5, 15, 5, 15);

        txtName.setBackground(textFieldBackground);
        txtName.setForeground(textColor);
        txtName.setBorder(textFieldBorder);
        txtTicket.setBackground(textFieldBackground);
        txtTicket.setForeground(textColor);
        txtTicket.setBorder(textFieldBorder);
        txtTicketID.setBackground(textFieldBackground);
        txtTicketID.setForeground(textColor);
        txtTicketID.setBorder(textFieldBorder);
        txtResolved.setBackground(textFieldBackground);
        txtResolved.setForeground(textColor);
        txtResolved.setBorder(textFieldBorder);
        txtComment.setBackground(textFieldBackground);
        txtComment.setForeground(textColor);
        txtComment.setBorder(textFieldBorder);
        txtSearchTicketID.setBackground(textFieldBackground);
        txtSearchTicketID.setForeground(textColor);
        txtSearchTicketID.setBorder(textFieldBorder);

        // Set button style
        Color buttonBackground = new Color(52, 152, 219);
        Color buttonTextColor = new Color(255, 255, 255);
        Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

        btnSearchTicketID.setBackground(buttonBackground);
        btnSearchTicketID.setForeground(buttonTextColor);
        btnSearchTicketID.setBorder(buttonBorder);
        btnBack.setBackground(buttonBackground);
        btnBack.setForeground(buttonTextColor);
        btnBack.setBorder(buttonBorder);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchTicketID;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JLabel lblTicketID;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblViewTickets;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtResolved;
    private javax.swing.JTextField txtSearchTicketID;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtTicketID;
    // End of variables declaration//GEN-END:variables
}
