/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Student;
import Business.Admin.TicketManager;
import Business.Admin.ViewTicketAdminJPanel;
import Business.Professor.Course;
import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author anzal
 */
public class ViewStudentPortalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentPortalJPanel
     */
    javax.swing.JPanel workArea;
    StudentLoginHistory history;
    private studentLogin loggedInUser;
    EnrollmentHistory enrollmentList;
    CourseHistory c_history;
    private ProfessorLogin proflogin;
    ProfessorLoginHistory history1;
    private Enrollment enroll;
    TicketManager ticketManager;
//    private Course cos;
    
    public ViewStudentPortalJPanel(JPanel workArea, StudentLoginHistory history,studentLogin loggedInUser,EnrollmentHistory enrollmentList,CourseHistory c_history,ProfessorLogin proflogin,ProfessorLoginHistory history1,Enrollment enroll,TicketManager ticketManager) {
        initComponents();
        this.workArea = workArea;
        this.loggedInUser = loggedInUser;
        this.history = history;
        this.enrollmentList = enrollmentList;
        this.c_history = c_history;
        this.proflogin = proflogin;
        this.history1 = history1;
        this.enroll = enroll;
        this.ticketManager = ticketManager;
        customizeComponents();
       // this.cos = cos;
       
       btnInbox.setVisible(false);
       btnSentbox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistration = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnManageAcc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnViewAccount = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnCourseWork = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnInbox = new javax.swing.JButton();
        btnSentbox = new javax.swing.JButton();
        btnAnnouncements = new javax.swing.JButton();
        btnStudentCreateTickets = new javax.swing.JButton();
        btnStudentViewTickets = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT MODULE");

        btnRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/graduated.png"))); // NOI18N
        btnRegistration.setText("Enroll Course");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("My Account");

        btnManageAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/admin.png"))); // NOI18N
        btnManageAcc.setText("Manage Account");
        btnManageAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Student Operations");

        btnViewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/eye.png"))); // NOI18N
        btnViewAccount.setText("View Account");
        btnViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountActionPerformed(evt);
            }
        });

        btnDeleteAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/user.png"))); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        btnTranscript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/catalogue.png"))); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnCourseWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/schedule.png"))); // NOI18N
        btnCourseWork.setText("Course Schedule");
        btnCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseWorkActionPerformed(evt);
            }
        });

        btnWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/logout.png"))); // NOI18N
        btnWithdraw.setText("Withdraw ");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnInbox.setText("Inbox");

        btnSentbox.setText("Sentbox");

        btnAnnouncements.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/megaphone.png"))); // NOI18N
        btnAnnouncements.setText("Check Announcements");
        btnAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnouncementsActionPerformed(evt);
            }
        });

        btnStudentCreateTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/support-ticket.png"))); // NOI18N
        btnStudentCreateTickets.setText("Create Tickets");
        btnStudentCreateTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCreateTicketsActionPerformed(evt);
            }
        });

        btnStudentViewTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/icons/ticket.png"))); // NOI18N
        btnStudentViewTickets.setText("View Tickets");
        btnStudentViewTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewTicketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSentbox))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnManageAcc)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewAccount)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                        .addComponent(btnInbox)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTranscript)
                        .addGap(18, 18, 18)
                        .addComponent(btnCourseWork)
                        .addGap(18, 18, 18)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnnouncements)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudentCreateTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudentViewTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnouncements, btnCourseWork, btnDeleteAccount, btnManageAcc, btnRegistration, btnStudentCreateTickets, btnStudentViewTickets, btnTranscript, btnViewAccount, btnWithdraw});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInbox, btnSentbox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManageAcc)
                            .addComponent(btnViewAccount)
                            .addComponent(btnDeleteAccount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnInbox)
                        .addGap(99, 99, 99)
                        .addComponent(btnSentbox)))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistration)
                    .addComponent(btnTranscript)
                    .addComponent(btnCourseWork)
                    .addComponent(btnWithdraw))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentCreateTickets)
                    .addComponent(btnAnnouncements)
                    .addComponent(btnStudentViewTickets))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnnouncements, btnCourseWork, btnDeleteAccount, btnManageAcc, btnRegistration, btnStudentCreateTickets, btnStudentViewTickets, btnTranscript, btnViewAccount, btnWithdraw});

    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        // TODO add your handling code here:
        StudentRegistrationPageJPanel panel = new StudentRegistrationPageJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("StudentRegistrationPageJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnManageAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccActionPerformed
        // TODO add your handling code here:
        ManageStudentAccountJPanel panel = new ManageStudentAccountJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("ManageStudentAccountJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageAccActionPerformed

    private void btnViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountActionPerformed
        // TODO add your handling code here:
        ViewAccountJPanel panel = new ViewAccountJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("ManageStudentAccountJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        // TODO add your handling code here:
        // Delete the logged-in user
        
        int dailogButton = JOptionPane.YES_NO_OPTION;
            int dailogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account details?","Warning",dailogButton);
            
            if(dailogResult == JOptionPane.YES_OPTION){
        history.deleteStudent(loggedInUser);
        history.refreshHistory();
        
        JOptionPane.showMessageDialog(this, "User deleted Successfully");
        StudentLoginPageJPanel panel = new StudentLoginPageJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("StudentLoginJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
            }
        
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        StudentTranscriptJPanel panel = new StudentTranscriptJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("StudentTranscriptJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnCourseWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseWorkActionPerformed
        // TODO add your handling code here:
        StudentCourseWorkJPanel panel = new StudentCourseWorkJPanel(workArea,history,loggedInUser,enrollmentList, c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("StudentCourseWorkJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCourseWorkActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        WithdrawStudentCourseJPanel panel = new WithdrawStudentCourseJPanel(workArea,history,loggedInUser,enrollmentList,c_history,proflogin,history1,enroll,ticketManager);
        workArea.add("WithdrawStudentCourseJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnouncementsActionPerformed
        // TODO add your handling code here:
        
        ViewAnnouncementJPanel panel = new ViewAnnouncementJPanel(workArea,history1,proflogin,c_history,history,loggedInUser,enrollmentList,enroll,ticketManager);
        workArea.add("ViewAnnouncementJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnAnnouncementsActionPerformed

    private void btnStudentCreateTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCreateTicketsActionPerformed
        // TODO add your handling code here:
        StudentCreateTicketJPanel panel = new StudentCreateTicketJPanel(workArea, history, loggedInUser, proflogin, history1, enrollmentList,c_history,enroll);
        workArea.add("AdminCreateTicketJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnStudentCreateTicketsActionPerformed

    private void btnStudentViewTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewTicketsActionPerformed
        // TODO add your handling code here:
        TicketManager ticketManager = TicketManager.getInstance();
        StudentViewTicketJPanel panel = new StudentViewTicketJPanel(workArea, ticketManager, history, loggedInUser, proflogin, history1, enrollmentList,c_history,enroll);
        workArea.add("ViewTicketAdminJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnStudentViewTicketsActionPerformed

private void customizeComponents() {
    // Set background color
    this.setBackground(new Color(44, 62, 80));

    // Set font and text color for labels
    Font labelFont = new Font("Tahoma", Font.BOLD, 12);
    Color textColor = new Color(236, 240, 241);

    jLabel1.setFont(new Font("Tahoma", Font.BOLD, 28));
    jLabel1.setForeground(textColor);
    jLabel2.setFont(labelFont);
    jLabel2.setForeground(textColor);
    jLabel3.setFont(labelFont);
    jLabel3.setForeground(textColor);

    // Set button style
    Color buttonBackground = new Color(52, 152, 219);
    Color buttonTextColor = new Color(255, 255, 255);
    Border buttonBorder = BorderFactory.createEmptyBorder(10, 25, 10, 25);

    btnRegistration.setBackground(buttonBackground);
    btnRegistration.setForeground(buttonTextColor);
    btnRegistration.setBorder(buttonBorder);
    btnManageAcc.setBackground(buttonBackground);
    btnManageAcc.setForeground(buttonTextColor);
    btnManageAcc.setBorder(buttonBorder);
    btnViewAccount.setBackground(buttonBackground);
    btnViewAccount.setForeground(buttonTextColor);
    btnViewAccount.setBorder(buttonBorder);
    btnDeleteAccount.setBackground(buttonBackground);
    btnDeleteAccount.setForeground(buttonTextColor);
    btnDeleteAccount.setBorder(buttonBorder);
    btnTranscript.setBackground(buttonBackground);
    btnTranscript.setForeground(buttonTextColor);
    btnTranscript.setBorder(buttonBorder);
    btnCourseWork.setBackground(buttonBackground);
    btnCourseWork.setForeground(buttonTextColor);
    btnCourseWork.setBorder(buttonBorder);
    btnWithdraw.setBackground(buttonBackground);
    btnWithdraw.setForeground(buttonTextColor);
    btnWithdraw.setBorder(buttonBorder);
    btnInbox.setBackground(buttonBackground);
    btnInbox.setForeground(buttonTextColor);
    btnInbox.setBorder(buttonBorder);
    btnSentbox.setBackground(buttonBackground);
    btnSentbox.setForeground(buttonTextColor);
    btnSentbox.setBorder(buttonBorder);
    btnAnnouncements.setBackground(buttonBackground);
    btnAnnouncements.setForeground(buttonTextColor);
    btnAnnouncements.setBorder(buttonBorder);
    btnStudentCreateTickets.setBackground(buttonBackground);
    btnStudentCreateTickets.setForeground(buttonTextColor);
    btnStudentCreateTickets.setBorder(buttonBorder);
    btnStudentViewTickets.setBackground(buttonBackground);
    btnStudentViewTickets.setForeground(buttonTextColor);
    btnStudentViewTickets.setBorder(buttonBorder);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnouncements;
    private javax.swing.JButton btnCourseWork;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnManageAcc;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnSentbox;
    private javax.swing.JButton btnStudentCreateTickets;
    private javax.swing.JButton btnStudentViewTickets;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JButton btnViewAccount;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
