/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Business;

import Business.Admin.AdminLoginPageJPanel;
import Business.Admin.TicketManager;
import Business.Professor.Course;
import Business.Professor.CourseHistory;
import Business.Professor.ProfessorLogin;
import Business.Professor.ProfessorLoginHistory;
import Business.Professor.ProfessorLoginPageJPanel;
import Business.Student.Enrollment;
import Business.Student.EnrollmentHistory;
import Business.Student.StudentLoginHistory;
import Business.Student.StudentLoginPageJPanel;
import Business.Student.studentLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;

/**
 *
 * @author anzal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    StudentLoginHistory history;
    ProfessorLoginHistory history1;
    private studentLogin loggedInUser;
    EnrollmentHistory enrollmentList;
    private ProfessorLogin loggedinUser;
    CourseHistory c_history;
    private Course cos;
    private Enrollment enroll;
    TicketManager ticketManager;
    
    public MainJFrame() {
        initComponents();
        history = new StudentLoginHistory();
        history1 = new ProfessorLoginHistory();
        enrollmentList = new EnrollmentHistory();
        c_history = new CourseHistory();
        loggedinUser = new ProfessorLogin();
        loggedInUser = new studentLogin();
        customizeUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnProfLogin = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        btnStudentLogin = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(204, 255, 255));

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignUp.setText("SignUp");
        btnSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnProfLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfLogin.setText("Professor Login");
        btnProfLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfLoginActionPerformed(evt);
            }
        });

        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudentLogin.setText("Student Login");
        btnStudentLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfLogin)
                    .addComponent(btnAdminLogin)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminLogin, btnProfLogin, btnSignUp, btnStudentLogin});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProfLogin)
                .addGap(18, 18, 18)
                .addComponent(btnAdminLogin)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdminLogin, btnProfLogin, btnSignUp, btnStudentLogin});

        splitPane.setLeftComponent(controlPanel);

        workArea.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO SAZ E-LEARNING PLATFORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        workArea.add(jPanel1, "card3");

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfLoginActionPerformed
        // TODO add your handling code here:
        
        ProfessorLoginPageJPanel panel = new ProfessorLoginPageJPanel(workArea,history1,loggedinUser,c_history,cos,history,loggedInUser,enrollmentList,enroll);
        workArea.add("ProfessorLoginJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnProfLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        
        AdminLoginPageJPanel panel = new AdminLoginPageJPanel(workArea,history,loggedInUser,loggedinUser,history1,enrollmentList,ticketManager,c_history);
        workArea.add("AdminLoginJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLoginActionPerformed
        // TODO add your handling code here:

        StudentLoginPageJPanel panel = new StudentLoginPageJPanel(workArea,history,loggedInUser,enrollmentList,c_history,loggedinUser,history1,enroll,ticketManager);
        workArea.add("StudentLoginJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnStudentLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        
        SignUpPageJPanel panel = new SignUpPageJPanel(history,workArea,history1,loggedinUser,loggedInUser);
        workArea.add("SignUpPageJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    private void customizeUI() {
        // Set background color
        controlPanel.setBackground(new Color(44, 62, 80));
        workArea.setBackground(new Color(44, 62, 80));

        // Set font and text color for buttons
        Font buttonFont = new Font("Tahoma", Font.BOLD, 12);
        Color buttonTextColor = new Color(236, 240, 241);
        btnSignUp.setFont(buttonFont);
        btnSignUp.setForeground(buttonTextColor);
        btnProfLogin.setFont(buttonFont);
        btnProfLogin.setForeground(buttonTextColor);
        btnAdminLogin.setFont(buttonFont);
        btnAdminLogin.setForeground(buttonTextColor);
        btnStudentLogin.setFont(buttonFont);
        btnStudentLogin.setForeground(buttonTextColor);

        // Set button background color and border
        Color buttonBackgroundColor = new Color(52, 73, 94);
        btnSignUp.setBackground(buttonBackgroundColor);
        btnSignUp.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        btnProfLogin.setBackground(buttonBackgroundColor);
        btnProfLogin.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        btnAdminLogin.setBackground(buttonBackgroundColor);
        btnAdminLogin.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        btnStudentLogin.setBackground(buttonBackgroundColor);
        btnStudentLogin.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));

        // Set label styles
        jLabel1.setForeground(new Color(236, 240, 241));
        jLabel1.setFont(new Font("Calibri", Font.BOLD, 36));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnProfLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnStudentLogin;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
